import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { appwrite, Collections } from "global/appwrite";
import styles from "styles/Home.module.css";
import { postData } from "utils/api";
import { Query } from "appwrite";
const Home: NextPage = () => {
  // const createUser = () => {
  //   appwrite.account
  //     .create("unique()", "me@example.com", "password", "Jane Doe")
  //     .then(
  //       (response) => {
  //         console.log(response);
  //       },
  //       (error) => {
  //         console.log(error);
  //       }
  //     );
  // };

  const createRoom = async () => {
    const account = await appwrite.account.get();

    await postData("/api/createRoom/", {
      owner: account.$id,
    });
  };

  const getRoom = async () => {
    const account = await appwrite.account.get();
    console.log(account);
    // const room = await appwrite.database.listDocuments(Collections.Room, [
    //   Query.equal("code", "3"),
    // ]);
    // console.log(room);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>PvP Logo Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={getRoom}>Click me to get your room</button>
      {/* <button onClick={createUser}>Click me to create user</button> */}
      {/* TODO */}
      {/* <p>Players online: </p> */}
      <main className={styles.main}>
        <button onClick={createRoom}>Play with BOT</button>
        <button>Enter Matchmaking</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
